--- #YAML:1.0
name:               Method-Lexical
version:            0.23
abstract:           private methods and lexical method overrides
author:
    - chocolateboy <chocolate@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    B::Hooks::OP::Annotation:  0.43
    B::Hooks::OP::Check:  0.18
    ExtUtils::Depends:    0.304
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Hooks::EndOfScope:  0.09
    B::Hooks::OP::Annotation:  0.43
    B::Hooks::OP::Check:  0.18
    Devel::Pragma:        0.54
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
