---
abstract: 'private methods and lexical method overrides'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  B::Hooks::OP::Annotation: 0.44
  B::Hooks::OP::Check: 0.19
  ExtUtils::Depends: 0.304
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Method-Lexical
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::EndOfScope: 0.12
  B::Hooks::OP::Annotation: 0.44
  B::Hooks::OP::Check: 0.19
  Devel::Pragma: 0.54
resources:
  repository: http://github.com/chocolateboy/Method-Lexical
version: 0.30
